###Get Resources
GET http://localhost:5229/resources

###Get Resource by ID
GET http://localhost:5229/resources/5

### Create a new Resource
POST http://localhost:5229/resources
Content-Type: application/json

{
  "name": "Hats",
  "quantity": 5,
  "locationId": 2
}

### Update a Resource
PUT http://localhost:5229/resources/5
Content-Type: application/json

{
  "name": "Tshirts and bags",
  "quantity": 50,
  "locationId": 2
}

###Delete Resource by ID
DELETE http://localhost:5229/resources/5