###Get Resources
GET http://localhost:5229/resources

###Get Resource by ID
GET http://localhost:5229/resources/5

### Create a new Resource
POST http://localhost:5229/resources
Content-Type: application/json

{
  "name": "Hats",
  "quantity": 5,
  "locationId": 2
}

### Update a Resource
PUT http://localhost:5229/resources/5
Content-Type: application/json

{
  "name": "Tshirts and bags",
  "quantity": 50,
  "locationId": 2
}

###Delete Resource by ID
DELETE http://localhost:5229/resources/5


###Get Locations
GET http://localhost:5229/locations

###Get Locations by ID
GET http://localhost:5229/locations/2

### Post Location
POST http://localhost:5229/locations
Content-Type: application/json

{
  "name": "Compartment 22"
}

### Update a location
PUT http://localhost:5229/locations/7
Content-Type: application/json

{
  "name": "Compartment No 22"
}

###Delete Resource by ID
DELETE http://localhost:5229/locations/6

###Get Bookings
GET http://localhost:5229/Bookings

###POST Bookings
POST http://localhost:5229/Bookings
Content-Type: application/json

{
  "newBooking": {
    "personName": "John Doe",
    "contactNumber": "123-456-7890",
    "collectionDate": "2024-07-10",
    "returnDate": "2024-07-15",
    "class_dept": "Engineering"
  },
  "resource": {
    "Id": 1
  }
}
